### ISSUE TITLE
Python: ImportError: No module named pipeline

### ISSUE THREAD

**Issue by fcaldas** [GoogleCloudPlatform/appengine-mapreduce#100]
Hi,

  I am trying to develop a simple application that updates a group of records on Google Datastore and for that I created an application, cloned this repository and copied ```appengine-mapreduce/python/src/mapreduce``` to my application root directory.

  I then updated my ```app.yaml``` to add the include, it looks like this:

```
application: guestbook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

includes:
- mapreduce/include.yaml

handlers:
- url: /
  script: guestbook.app
- url: /mapmatch
  script: mapreduce.app
  login: admin
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: latest

builtins:
- remote_api: on
- deferred: on
```

The problem is: as far as I understand I should see something on ```myapp.com/mapreduce``` but all I get is the following error message:

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/e~xxxxx-test/v1.394666648272080269/mapreduce/main.py", line 39, in <module>
    from mapreduce import handlers
  File "/base/data/home/apps/e~xxxxx-test/v1.394666648272080269/mapreduce/handlers.py", line 46, in <module>
    from mapreduce import base_handler
  File "/base/data/home/apps/e~xxxxx-test/v1.394666648272080269/mapreduce/base_handler.py", line 37, in <module>
    pipeline_base = importlib.import_module('mapreduce.pipeline_base')
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/base/data/home/apps/e~xxxxx-test/v1.394666648272080269/mapreduce/pipeline_base.py", line 18, in <module>
    import pipeline
ImportError: No module named pipeline
```

Did I miss something during the setup?

**Comment by fcaldas** [comment]
After copying the other libraries from ```appengine-mapreduce/python/src/``` it worked.

**Comment by peterchen16** [comment]
I have the same problem, there's only two other py files under src folder, distribute_setup.py and setup.py, what should I do with them?
