### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Erfa** [GoogleCloudPlatform/appengine-mapreduce#105]
It appears to me that this is a lib that has a history of changing a lot on how you are supposed to install it. The documentation (which I doubt is up to date?) didn't help much at all, so instead I did it like you normally do for python libs - add it to your requirements.txt. Didn't work that well, I get this error when trying to run it:
```
Traceback (most recent call last):
  File "/home/erfa/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/home/erfa/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/home/erfa/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/home/erfa/mapreduce-test/app.py", line 3, in <module>
    from google.appengine.ext.mapreduce.mapreduce_pipeline import MapreducePipeline
  File "/home/erfa/google_appengine/google/appengine/ext/mapreduce/mapreduce_pipeline.py", line 48, in <module>
    from appengine_pipeline.src import pipeline
ImportError: No module named appengine_pipeline.src
```

I got similar problems when trying to do it like in the documentation. Any ideas? Almost all information I find when trying to Google this lib seems outdated.

My approach is here by the way:
https://github.com/Erfa/mapreduce-test

**Comment by Erfa** [comment]
Update: I think I figured out the cause of that import error, but that only lead to another one. Now I get this when trying to start the pipeline:
```
Traceback (most recent call last):
  File "/home/erfa/mapreduce-test/lib/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erfa/mapreduce-test/lib/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erfa/mapreduce-test/lib/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/erfa/mapreduce-test/lib/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erfa/mapreduce-test/lib/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/erfa/mapreduce-test/app.py", line 44, in hello_world
    pipeline.start()
  File "/home/erfa/mapreduce-test/lib/mapreduce/pipeline_base.py", line 21, in start
    return pipeline.Pipeline.start(self, **kwargs)
  File "/home/erfa/mapreduce-test/lib/pipeline/pipeline.py", line 673, in start
    self, idempotence_key, str(e)))
PipelineSetupError: Error starting app.Pipeline(*(), **{})#93203bf40c6c4d678525c2dac719843c:
```

It appears to be the same issue as #103, which has no answer yet. Any ideas?

**Comment by Erfa** [comment]
Confirmed to be a duplicate of #103.
