### ISSUE TITLE
Python: build.sh crashes at the end

### ISSUE THREAD

**Issue by pipacs** [GoogleCloudPlatform/appengine-mapreduce#70]
When ran as non-root (as instructed):

$ sh build.sh build_demo

...

Cleaning up...
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1294, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 525, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1639, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/util.py", line 294, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

Storing complete log in /Users/polster/Library/Logs/pip.log

**Comment by tkaitchuck** [comment]
Why are you running it as root? Where does it say that?
If you run as non-root it should pull the dependencies into the local directory.
It does an rm on the dependency directory before building. This is to work around a bug in pip where it fails to upgrade an existing version and instead puts the new version inside of it. 

We could suppress the error if rm fails. However it will cause pip not upgrade libraries and fail on the second build in the next step where it tries to overwrite the directory, that it downloaded and put inside the directory that it was supposed to upgrade.

**Comment by pipacs** [comment]
Please read the issue again. It's about running build.sh as NON-root.

**Comment by tkaitchuck** [comment]
Humm. That is odd. I've added six on the list of things to delete. See if that helps. It is an old version of six, if all else fails removing it manually, should get things working... 

I don't really understand that path. Why is it looking in:
'/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/'

What OS are you using? Also what do you get as the output to:
pip --version

**Comment by pipacs** [comment]
Path looks standard to me: it's OS X Yosemite. pip --version says:

pip 1.4.1 from /Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg (python 2.7)

**Comment by tkaitchuck** [comment]
Try getting a newer version of PIP. I had a lot of problems with the older versions.
